package com.myspace.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quote implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Eligibility")
	private java.lang.String eligibility;
	@org.kie.api.definition.type.Label("Premium")
	private double premium;

	public Quote() {
	}

	public java.lang.String getEligibility() {
		return this.eligibility;
	}

	public void setEligibility(java.lang.String eligibility) {
		this.eligibility = eligibility;
	}

	public double getPremium() {
		return this.premium;
	}

	public void setPremium(double premium) {
		this.premium = premium;
	}

	public Quote(java.lang.String eligibility, double premium) {
		this.eligibility = eligibility;
		this.premium = premium;
	}

}